### ISSUE TITLE
Can't save experiment

### ISSUE THREAD

**Issue by cristian-tamblay** [DashAISoftware/DashAI#98]
* Python version:3.8
* Operating System:Ubuntu20.04

### Description

Tried to save a new experiment with models, threw error:
![image](https://github.com/DashAISoftware/DashAI/assets/30818944/7db833bd-f5d3-4722-bb2d-a4aa1c35dc8d)

**Comment by maximi4321** [comment]
This problem should be solved when pr #96 is merged.
